# Generated by Django 5.0 on 2023-12-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbrand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
