# Generated by Django 5.0 on 2023-12-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbrand', '0002_alter_carbrand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbrand',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
