# Generated by Django 5.0 on 2023-12-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbrand', '0003_carbrand_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
