# Generated by Django 5.0 on 2023-12-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmodel', '0002_carmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
