# Generated by Django 5.0 on 2023-12-19 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmodel', '0004_alter_carmodel_image_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('Carmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='carmodel.carmodel')),
            ],
        ),
    ]
